### ISSUE TITLE
[Matplotlib] Uncorrect type-hint in `font_manager.FontProperties`

### ISSUE THREAD

**Issue by I-love-study** [microsoft/python-type-stubs#240]
In `matplotlib.font_manager.FontProperties`, Type-hint for `fname` arg is `PosixPath | None` (Also in `FontProperties.set_file`)
However, In method, it should be support more than `PosixPath | None` (Like `str` and `WindowsPath`)

``` python
def set_file(self, file):
    """
    Set the filename of the fontfile to use.  In this case, all
    other properties will be ignored.
    """
    self._file = os.fspath(file) if file is not None else None
```

Sorry for the poor English cuz I'm not native speaker.

**Comment by Avasam** [comment]
Given that « matplotlib 3.8 will ship with typing stubs » (https://github.com/matplotlib/matplotlib/issues/24701#issuecomment-1530126439), you can try the in-development version using `pip install git+https://github.com/matplotlib/matplotlib.git#egg=matplotlib`.

It should work as-is with pyright and mypy, but for Pylance you'll have to remove the bundled stubs everytime you update the extension. it can be found at: `%HOMEPATH%\.vscode\extensions\ms-python.vscode-pylance-<VERSION>\dist\bundled\stubs\matplotlib` (where `<VERSION>` is your current Pylance version).

If the issue persists, you can raise it upstream.

**Comment by debonte** [comment]
matplotlib 3.8.0 has shipped and contains their own stubs. We are continuing to ship our stubs for the benefit of users on earlier versions, but we are not planning to make enhancements to them in the future. If our stubs are insufficient for your purposes, you should upgrade to 3.8.0+ and file issues against matplotlib for any improvements that are needed.

> for Pylance you'll have to remove the bundled stubs everytime you update the extension

This is not necessary because matplotlib 3.8.0 is `py.typed` and therefore Pylance will prefer the types provided by the library over our bundled stubs.
